### PR TITLE
2.0.0 beta

### PR DESCRIPTION
**Pull request by natebird**
Updates to comply with beta dependencies.

### CODE REVIEW

**Comment by natebird** [comment]
I can't seem to get CircleCI to run on PR for this project? And Travis fails on the macOS build even though it works fine locally.

Update: I fixed CircleCI with a project configuration change.

**Comment by 0xTim** [comment]
@natebird have you tried changing the Xcode version in your travis.yml file to `xcode8.3` as per https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version? I'm wondering if it's trying to build it with a Swift 3.0 toolchain

**Comment by 0xTim** [comment]
So for some reason it is still running on Swift 3.0 https://travis-ci.org/vapor/postgresql/jobs/218840790#L65, which is confusing!

**Comment by 0xTim** [comment]
Ah you're ca16f31 commit has removed the `xcode8.3` OS X image specifier?

**Comment by 0xTim** [comment]
(You can do `git commit --allow-empty` to kick build systems with an empty commit)

**Comment by natebird** [comment]
@0xTim yeah, It didn't build postgres with the xcode8.3 option. Trying again.

**Comment by natebird** [comment]
@0xTim yep. same thing again. Postgres isn't starting. https://travis-ci.org/vapor/postgresql/jobs/218843500

**Comment by 0xTim** [comment]
Hmm that's frustrating!

**Comment by natebird** [comment]
Current status: Kicking Travis until it does what I want.

**Pull request merged**
