### PR TITLE
Fixed handling of data by parsing string to bytes

### PR DESCRIPTION
**Pull request by sroebert**
This pull request fixes the handling of data as `[UInt8]`. It was not handled correctly before.

### CODE REVIEW

**Comment by sroebert** [comment]
Ok, when I was writing the unit tests for this, it seems there is a bigger problem with `[UInt8]` data. When binding parameters, all data is transformed into strings before send to postgres. This results in issues when retrieving the data later again. I think it would be nice to look into sending data where possible as binary data. I'll have a look at updating this pull request.

**Comment by sroebert** [comment]
Ok, I ended up changing the code for binding blob data for postgres, to actually use the byte representation directly, instead of a string (while at the same time cleaning that code up a bit). For retrieving the blob data from a string from postgres, the string had to be converted from a hex string back into bytes.

**Comment by natebird** [comment]
@sroebert thanks for going through this thoroughly. When I was getting this ready for a 1.0 release it was mainly just getting the tests to pass without understanding all the nuances. Glad you have the expertise to recognize the issues.

This looks great. 👍

**Comment by sroebert** [comment]
@natebird While working on this I was also looking into working fully with binary data. This does however require to fully support all postgres types (e.g. UUID, date, time). By working with strings, you at least can use the string representation of those.

I still think this would be a nice addition, as it will boost performance by not having to transform between data types and strings. I'll have a look at making a pull request for this if you guys think it is a good direction.

**Comment by tanner0101** [comment]
This looks great! Is there any way we can default to using String equivalent if the value is unsupported (for UUID, date, time, etc?) and keep the better performance for the supported types?

**Comment by sroebert** [comment]
Unfortunately not, with the library it is either string or binary. You could write your own connection, but then still you need to know up front the type of the column. I don't think it is a lot of work to support all types in binary format though. It is quite well documented.

**Comment by tanner0101** [comment]
The public API hasn't changed at all right? If so, we should be good to merge and tag this as 1.1.

**Review by tanner0101 — APPROVED** [review]

**Pull request merged**
