### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by natebird**
- Remove unnecessary db user  creation from circleCI config.
- Remove unnecessary loop for deallocating pointers in execute function.

### CODE REVIEW

**Comment by tanner0101** [comment]
How is the loop unnecessary?

**Comment by natebird** [comment]
I removed it and everything still passes and works just fine locally and in CI. The loop in the bind statement is still needed.

**Comment by tanner0101** [comment]
Everything should work fine with or without it, but without it there may be a memory leak. I'm not 100% sure but we should verify before we remove it.

**Comment by natebird** [comment]
This isn't necessary with the changes from #19

**Pull request closed without merging**
