### PR TITLE
Update for Swift 5.

### PR DESCRIPTION
**Pull request by ken-broadsheet**
Updates source and Package.swift for Swift 5 compatibility.

### CODE REVIEW

**Comment by 0xTim** [comment]
To avoid breaking any old existing clients, it's probably best to have this as a `Package@swift-5.swift` manifest in addition to the existing one

**Comment by ken-broadsheet** [comment]
Done – this may break Swift 3 anyway due to the code changes, so it'd probably be best to release as a new major version.

**Comment by 0xTim** [comment]
Ah yeah - what are you using this project for by the way? I'm not sure whether a release will happen as this is a Vapor 2 package that is long past it's EOL

**Comment by ken-broadsheet** [comment]
I'm using it for a project with a Google CloudSQL database. I chose this over Swift-Kuery because it doesn't do stupid things with async dispatch.

I just noticed https://github.com/PerfectlySoft/Perfect-PostgreSQL, which might also work for me.

**Comment by 0xTim** [comment]
Yeah the whole server-side Swift industry is moving to libraries based on NIO - [this](https://github.com/vapor/postgres-nio) is the one that's been pitched to the SSWG

**Comment by 0xTim** [comment]
PS, we can make the changes non-breaking by using compiler directives to switch on the version of Swift

**Comment by ken-broadsheet** [comment]
Done.

**Review by 0xTim — APPROVED** [review]
Thanks!

**Comment by 0xTim** [comment]
This is released as [2.2.0](https://github.com/vapor-community/postgresql/releases/tag/2.2.0)

**Comment by ken-broadsheet** [comment]
Thank you!

**Pull request merged**
