### PR TITLE
Feature/binary support

### PR DESCRIPTION
**Pull request by sroebert**
Binary support for (pretty much) all types.
- Encoding all types that make sense in binary form.
- Decoding all types from binary and converting to string where necessary. This will make it much easier to for example fully support more types (e.g. dates, uuid's) in the future.
- Unit tests for all binary parsing.
- Array support (encoding and decoding), allowing to put any of the supported types in a (multi-dimensional) array.

- Removal of dependency on Core.

Currently this pull request has public API changes. This is only the case because I made some API internal, which should not have been public in the first place. If needed, I can update to make sure the public API does not change.

I feel however, this is cleaner and should not really break anyone's implementation. The two things I removed from being public are `Result` and `OID`. `Result` was already unusable as the `init` method was `internal`, so this should not be a problem for anyone. The `OID` enum was not used in any of the public API, so if anyone needs it in their code, a simple copy should work.

I would like some input on breaking the public API.

### CODE REVIEW

**Comment by sroebert** [comment]
I see some issues on Linux, will have a look at that.

**Comment by sroebert** [comment]
I will have a look at the other Linux build failures tomorrow.

**Comment by tanner0101** [comment]
Removing OID and Result from being public sounds like a good idea. However, what was the reasoning for removing dependency from Core?

**Comment by sroebert** [comment]
There was never a reason to include Core in the first place, it was not used. I can put it back if there was a good reason for it.

**Comment by tanner0101** [comment]
It's really useful for doing stuff like:

``` swift
let hexString = bytes.map { $0.lowercaseHexPair }.joined()
```

There's all sorts of conveniences like `bytes.hexString`, etc. that are well tested.

**Comment by sroebert** [comment]
Makes sense, I'll update that then.

**Comment by tanner0101** [comment]
I'm going to make a run through soon for all of the fluent drivers and make sure they pass the new Fluent tester. So I can go through at that point and update any spots where I think Core would be better. 

If you can just add it back to the Package.swift that would be enough. Of course, if you want to go through and try to update some of them that would be awesome. :)

**Comment by sroebert** [comment]
I had a look now and put back Core. There is however not much I can use. I did not see the `bytes.hexString` you mentioned.

Edit: Found it, it is actually in Vapor Essentials. Seems a bit overkill to import it. I see `lazy` is used there, which seems to have no added value.

**Comment by tanner0101** [comment]
Oops, yeah. I forgot we had been meaning to move that over to Core. Looks like it hasn't happened yet.

https://github.com/vapor/core/issues/18

The `.array` usage looks good. :)

You can merge this whenever. Let's wait to tag, though. I want to run it through the Fluent tester first.

**Pull request merged**
